language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.5
    - os: osx
      language: generic
      env: PYTHON_VER=3.6

    - os: linux
      python: 3.5
      env: PYTHON_VER=3.5
    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6

env:
  global:
    # Location of decrypted OpenEye license file
    - OE_LICENSE="$HOME/oe_license.txt"

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V
  # Get new encryption
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then  openssl aes-256-cbc -K $encrypted_ef0be1cff144_key -iv $encrypted_ef0be1cff144_iv -in oe_license.txt.enc -out oe_license.txt -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == false ]; then echo "OpenEye license will not be installed in forks."; fi


install:

    # Create test environment for package
  - conda create -n test python=$PYTHON_VER pip pytest pytest-cov
  - conda activate test

    # Install pip only modules
  - pip install codecov

   # Add channels
  - conda config --add channels conda-forge
  - conda config --add channels openeye

    # Build and install package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --use-local cmiles


script:
  - pytest -v --cov=cmiles cmiles/tests/

notifications:
    email: false

after_success:
  - codecov
