package:
  name: cmiles
  version: "0.1.0"

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - rdkit=2018.03.3
    - openeye-toolkits=2018.2.1

test:
  requires:
    - pytest
  imports:
    - cmiles

about:
  home: add_url_here
  license: MIT License
